# This is a deploy workflow to bump version

name: Bump Version

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version and commit
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version patch --git-tag-version false
          VERSION=$(node -p "require('./package.json').version")
          echo "module.exports = {" > version.js
          dateNow=$(date +"%Y-%m-%d")
          echo "    releaseDate:'${dateNow}'," >> version.js
          echo "    build:'${VERSION}-dev'" >> version.js
          echo "}" >> version.js
          git add version.js
          git add package.json
          git add package-lock.json
          git commit -m "bump version to ${VERSION}"
          git tag ${VERSION}
      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.MMELDO_PAT }}
          branch: ${{ inputs.branch }}
          tags: true
          unprotect_reviews: true      
