# This is a workflow to bump the version

name: CI Publish Prod

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm version patch --git-tag-version false
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: echo "module.exports = {" > version.js
      - run: dateNow=$(date +"%Y-%m-%d")
      - run: echo "    releaseDate:'${dateNow}'," >> version.js
      - run: echo "    build:'${VERSION}'" >> version.js
      - run: echo "}" >> version.js
      - run: git add version.js
      - run: git commit -m "bump version to ${VERSION}"
      - run: git tag ${VERSION}
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow in townsquare-client
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: townteki
          repo: townsquare-client
          github_token: ${{ secrets.MMELDO_PAT }}
          github_user: mmeldo
          workflow_file_name: publish-prod.yml
          ref: master
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
