# This is a deploy workflow to test server

name: Test Workflow

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bump-version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
      - run: sleep 30s
      - run: echo "TEST after SLEEP"
